apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world-service
  namespace: default
spec:
  ports:
  - name: hello-world
    port: 80
    targetPort: 8080
  selector:
    app: hello-world
  sessionAffinity: None
  type: ClusterIP

